networks:
  postgres-net:
    driver: bridge

volumes:
  postgres-vol:
    driver: local

services:

  postgres:
    image: postgres:16.1-alpine

    environment:
      PGPORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - postgres-vol:/var/lib/postgresql/data

    networks:
      - postgres-net

    expose:
      - "5432"

    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped


  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      NODE_ENV: production
      WB_API_TOKEN: ${WB_API_TOKEN}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: ${GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY}
      GOOGLE_SPREADSHEET_IDS: ${GOOGLE_SPREADSHEET_IDS}
      GOOGLE_SPREADSHEET_SHEET_NAME: ${GOOGLE_SPREADSHEET_SHEET_NAME}
      WB_TARIFFS_SYNC_CRON: ${WB_TARIFFS_SYNC_CRON}
      WB_TARIFFS_SYNC_RUN_ON_START: ${WB_TARIFFS_SYNC_RUN_ON_START}
      GOOGLE_SHEETS_SYNC_CRON: ${GOOGLE_SHEETS_SYNC_CRON}
      GOOGLE_SHEETS_SYNC_RUN_ON_START: ${GOOGLE_SHEETS_SYNC_RUN_ON_START}

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - postgres-net

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5

    restart: unless-stopped
